[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.3.0"}
remodel = { github = "rojo-rbx/remodel", version = "0.11.0"}
wally = {github = "UpliftGames/wally", version = "0.3.1" }
selene = {github = "Kampfkarren/selene", version = "0.19.1"}